version: '3.9'

services:
  ninja-backend:
    image: 'ninja/backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ninja-backend
    ports:
      - "80:80"
    depends_on:
      - ninja-db
    networks:
      - ninja_backend_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ninja-db:5432/ninja
  ninja-db:
    image: 'postgres:16.0-alpine'
    container_name: ninja-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ninja_backend_net
    environment:
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: ninja

volumes:
  db_data:

networks:
  ninja_backend_net: