version: '3.9'

services:
  ninja-backend:
    image: 'ninja/backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ninja-backend
    ports:
      - "80:80"
    depends_on:
      - ninja-db
      - ninja-cache
    networks:
      - ninja_backend_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ninja-db:5432/ninja
      SPRING_DATA_REDIS_HOST: ninja-cache
  ninja-db:
    image: 'postgres:16.0-alpine'
    container_name: ninja-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ninja_backend_net
    environment:
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: ninja
  ninja-cache:
    image: 'redis:7.2.3-alpine'
    container_name: ninja-cache
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    networks:
      - ninja_backend_net

volumes:
  db_data:
  cache_data:

networks:
  ninja_backend_net: